import type { PlaceSuggestion } from '@/types/place';

export const mockPlaces: PlaceSuggestion[] = [
    {
        id: 'place-1',
        place_id: 'place-1',
        name: 'เดอะคิวบ์ประชาอุทิศ',
        address: 'ราษฎร์บูรณะ, กทม',
        location: { lat: 13.6519, lng: 100.5045 },
        type: 'Attraction',
    },
    {
        id: 'place-2',
        place_id: 'place-2',
        name: 'เอเชียทีค เดอะ ริเวอร์ฟร้อนท์',
        address: 'วัดพระยาไกร, กทม',
        location: { lat: 13.7052, lng: 100.503 },
        type: 'Attraction',
    },
    {
        id: 'place-3',
        place_id: 'place-3',
        name: 'สยามพารากอน',
        address: 'ปทุมวัน, กทม',
        location: { lat: 13.7463, lng: 100.5347 },
        type: 'Attraction',
    },
    {
        id: 'place-4',
        place_id: 'place-4',
        name: 'เซ็นทรัลเวิลด์',
        address: 'ปทุมวัน, กทม',
        location: { lat: 13.7474, lng: 100.5392 },
        type: 'Attraction',
    },
    {
        id: 'place-5',
        place_id: 'place-5',
        name: 'จตุจักร',
        address: 'จตุจักร, กทม',
        location: { lat: 13.7995, lng: 100.5516 },
        type: 'Attraction',
    },
    {
        id: 'place-6',
        place_id: 'place-6',
        name: 'วัดอรุณราชวราราม',
        address: 'บางกอกใหญ่, กทม',
        location: { lat: 13.7437, lng: 100.4889 },
        type: 'Attraction',
    },
    {
        id: 'place-7',
        place_id: 'place-7',
        name: 'วัดพระแก้ว',
        address: 'พระนคร, กทม',
        location: { lat: 13.7515, lng: 100.4927 },
        type: 'Attraction',
    },
    {
        id: 'place-8',
        place_id: 'place-8',
        name: 'เยาวราช',
        address: 'สัมพันธวงศ์, กทม',
        location: { lat: 13.7384, lng: 100.5091 },
        type: 'Restaurant',
    },
    {
        id: 'place-9',
        place_id: 'place-9',
        name: 'ICONSIAM',
        address: 'คลองสาน, กทม',
        location: { lat: 13.7266, lng: 100.5104 },
        type: 'Attraction',
    },
    {
        id: 'place-10',
        place_id: 'place-10',
        name: 'Terminal 21 Asok',
        address: 'วัฒนา, กทม',
        location: { lat: 13.7379, lng: 100.5601 },
        type: 'Attraction',
    },
];
